### PR TITLE
2nd session arrange code

### PR DESCRIPTION
**Pull request by devmsh**
In the end of the 2nd session, we start working on the arrange phase of #2 scenario 1

First of all, we make new Unit Test class using
```
php artisan make:test FailedCourses --unit
```

Then we analyse the scenario 1 arrangement requirements and implement it using `Trainer`, `Course`, `Timeslot`, and `Interest` models.

We start creating the models with there corresponding `Factories` and `Migrations` using
```
php artisan make:model {ModelName} -mf
```

Now when we run the test, we need to use the `DatabaseMigrations` trait and using an sqlite in memory database in our testing environment.

After that we develop the migrations to create the `required` fields to make the test pass.

Finally, we are finished from the Arrange phase, and the current error must be about
```
BadMethodCallException : Call to undefined method valide()
```

### CODE REVIEW

**Comment by ahayek84** [comment]
Thank you for your precious effort my friend :) ... 

I have created all tables and fixed the PHPUnit configuration, but do you think that I need to seed the created tables ... :) in order to start testing data, ???

**Comment by devmsh** [comment]
@ahayek84 well done!

The seeders will be used to test the API manually and have some data to play with, currently we only use Factories to generate data specific for each test, no seeders needed in the TDD development unless we have some constants tables we need to feed with global data not related to each test.

We will discuss this more tomorrow

**Comment by ahayek84** [comment]
There is somthing interesting about USE data migration 

it drops all tables after the test is executed .. :| 

I wonder why ?

**Comment by devmsh** [comment]
@ahayek84 running your tests in old database will make it failed because of the old garbage content, we always assume that the database if fresh and clear, not only for each run, but also in each single test case or test function.

Hope you got it?

**Pull request closed without merging**
